#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LRXTrainerTools.Resource", IsApplication=true)]

namespace LRXTrainerTools
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int metronomeIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int stopwatch = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int stopwatchIcon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int clearButton = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int fragmentContainer = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int fullScreen = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int metStartButton = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int metStopButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int parentFrameLayout = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int relativeLayout1 = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int scrollView = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int startButton = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int stopButton = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int tempoBar = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int tempoText = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int timeLogText = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int timer = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int timerBackground = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int volText = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int volumeBar = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int metronomeView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int stopwatchView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int metTabText = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int stopwatchTabText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
